package com.example.safesos

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.ConnectivityManager
import android.net.NetworkCapabilities
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import android.telephony.SmsManager
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.viewModels
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import com.google.android.gms.location.LocationServices
import com.google.android.gms.location.Priority
import com.google.android.gms.tasks.CancellationTokenSource
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import org.json.JSONArray
import org.json.JSONObject
import kotlin.coroutines.resume

// ==========================================
// 1. DATA MODELS & STATE MACHINE DEFINITIONS
// ==========================================

enum class SOSState {
    IDLE,
    COUNTDOWN,
    ACTIVATED,
    ACTIVE_EMERGENCY,
    COMPLETED
}

enum class SharingDuration(val label: String, val minutes: Int) {
    ONCE("Share once", 0),
    MIN_15("15 minutes", 15),
    MIN_30("30 minutes", 30),
    HOUR_1("1 hour", 60),
    UNTIL_STOP("Until I stop it", -1)
}

data class EmergencyContact(
    val id: String,
    val name: String,
    val phone: String,
    val relationship: String,
    val isVerified: Boolean = false,
    val isPrimary: Boolean = false
)

data class SOSAlertMessage(
    val senderName: String,
    val timestamp: String,
    val latitude: Double,
    val longitude: Double,
    val accuracy: Float
) {
    // Plain ASCII only: keeps the alert on GSM-7 encoding so it doesn't silently
    // balloon into extra SMS segments (or get mangled) on some carriers.
    fun toFormattedString(): String {
        val mapsUrl = "https://maps.google.com/?q=$latitude,$longitude"
        return """
            EMERGENCY ALERT

            I may need help.

            Name: $senderName
            Time: $timestamp
            Location: $mapsUrl (+/-${accuracy.toInt()}m)

            Please contact me or call emergency services if necessary.

            This message was automatically generated by SafeSOS.
        """.trimIndent()
    }
}

// ==========================================
// 2. PRIVACY-FIRST ENCRYPTED LOCAL STORAGE
// ==========================================

class SecureStorage(context: Context) {
    private val masterKey = MasterKey.Builder(context)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    private val prefs = EncryptedSharedPreferences.create(
        context,
        "safe_sos_encrypted_prefs",
        masterKey,
        EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
        EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
    )

    fun saveContacts(contacts: List<EmergencyContact>) {
        val array = JSONArray()
        contacts.forEach { contact ->
            val obj = JSONObject().apply {
                put("id", contact.id)
                put("name", contact.name)
                put("phone", contact.phone)
                put("relationship", contact.relationship)
                put("isVerified", contact.isVerified)
                put("isPrimary", contact.isPrimary)
            }
            array.put(obj)
        }
        prefs.edit().putString("key_contacts", array.toString()).apply()
    }

    fun getContacts(): List<EmergencyContact> {
        val jsonString = prefs.getString("key_contacts", null) ?: return emptyList()
        val list = mutableListOf<EmergencyContact>()
        val array = JSONArray(jsonString)
        for (i in 0 until array.length()) {
            val obj = array.getJSONObject(i)
            list.add(
                EmergencyContact(
                    id = obj.getString("id"),
                    name = obj.getString("name"),
                    phone = obj.getString("phone"),
                    relationship = obj.getString("relationship"),
                    isVerified = obj.getBoolean("isVerified"),
                    isPrimary = obj.getBoolean("isPrimary")
                )
            )
        }
        return list
    }

    fun saveUserName(name: String) = prefs.edit().putString("key_user_name", name).apply()
    fun getUserName(): String = prefs.getString("key_user_name", "User") ?: "User"
}

// ==========================================
// 3. APPLICATION VIEWMODEL (State Engine)
// ==========================================

class SOSViewModel(private val applicationContext: Context) : ViewModel() {
    private val secureStorage = SecureStorage(applicationContext)
    private val fusedLocationClient = LocationServices.getFusedLocationProviderClient(applicationContext)

    private val _sosState = MutableStateFlow(SOSState.IDLE)
    val sosState: StateFlow<SOSState> = _sosState.asStateFlow()

    private val _countdownProgress = MutableStateFlow(0f)
    val countdownProgress: StateFlow<Float> = _countdownProgress.asStateFlow()

    private val _contacts = MutableStateFlow<List<EmergencyContact>>(emptyList())
    val contacts: StateFlow<List<EmergencyContact>> = _contacts.asStateFlow()

    private val _currentLocationText = MutableStateFlow("Obtaining location...")
    val currentLocationText: StateFlow<String> = _currentLocationText.asStateFlow()

    private val _selectedDuration = MutableStateFlow(SharingDuration.MIN_15)
    val selectedDuration: StateFlow<SharingDuration> = _selectedDuration.asStateFlow()

    private val _statusLog = MutableStateFlow<List<String>>(emptyList())
    val statusLog: StateFlow<List<String>> = _statusLog.asStateFlow()

    private var countdownJob: Job? = null

    init {
        _contacts.value = secureStorage.getContacts()
    }

    fun setSharingDuration(duration: SharingDuration) {
        _selectedDuration.value = duration
    }

    fun addContact(name: String, phone: String, relationship: String) {
        val newContact = EmergencyContact(
            id = System.currentTimeMillis().toString(),
            name = name,
            phone = phone,
            relationship = relationship,
            isVerified = true, // Auto-verified for demo simplicity
            isPrimary = _contacts.value.isEmpty()
        )
        val updated = _contacts.value + newContact
        _contacts.value = updated
        secureStorage.saveContacts(updated)
    }

    fun removeContact(id: String) {
        val updated = _contacts.value.filter { it.id != id }
        _contacts.value = updated
        secureStorage.saveContacts(updated)
    }

    fun startSOSPress() {
        if (_sosState.value != SOSState.IDLE) return

        // Guard against a stray job from a previous press still running.
        countdownJob?.cancel()

        _sosState.value = SOSState.COUNTDOWN
        countdownJob = viewModelScope.launch {
            val totalTime = 2000L // 2-second hold threshold
            val interval = 50L
            var elapsed = 0L

            while (elapsed < totalTime) {
                delay(interval)
                elapsed += interval
                _countdownProgress.value = elapsed.toFloat() / totalTime.toFloat()
            }

            triggerSOSActivation()
        }
    }

    fun cancelSOSPress() {
        if (_sosState.value == SOSState.COUNTDOWN) {
            countdownJob?.cancel()
            _sosState.value = SOSState.IDLE
            _countdownProgress.value = 0f
        }
    }

    private fun triggerSOSActivation() {
        _sosState.value = SOSState.ACTIVATED
        _statusLog.value = listOf("Initializing emergency protocol...")

        triggerVibration()

        viewModelScope.launch {
            appendLog("Acquiring GPS Signal...")
            val location = fetchCurrentLocation()

            val senderName = secureStorage.getUserName()
            val timeStr = java.text.SimpleDateFormat("HH:mm", java.util.Locale.getDefault()).format(java.util.Date())

            val alert = SOSAlertMessage(
                senderName = senderName,
                timestamp = timeStr,
                latitude = location?.latitude ?: 0.0,
                longitude = location?.longitude ?: 0.0,
                accuracy = location?.accuracy ?: 0f
            )

            if (location != null) {
                _currentLocationText.value =
                    "Lat: ${String.format("%.4f", location.latitude)}, Lon: ${String.format("%.4f", location.longitude)}"
                appendLog("[OK] Location obtained (+/-${location.accuracy.toInt()}m)")
            } else {
                _currentLocationText.value = "Location unavailable (Using fallback)"
                appendLog("[WARN] GPS fallback active")
            }

            appendLog("Evaluating network routes...")
            dispatchEmergencyAlert(alert)
        }
    }

    private suspend fun fetchCurrentLocation(): android.location.Location? {
        return suspendCancellableCoroutine { continuation ->
            val fineGranted = ContextCompat.checkSelfPermission(
                applicationContext, Manifest.permission.ACCESS_FINE_LOCATION
            ) == PackageManager.PERMISSION_GRANTED
            val coarseGranted = ContextCompat.checkSelfPermission(
                applicationContext, Manifest.permission.ACCESS_COARSE_LOCATION
            ) == PackageManager.PERMISSION_GRANTED

            if (!fineGranted && !coarseGranted) {
                continuation.resume(null)
                return@suspendCancellableCoroutine
            }

            // Only ask for high accuracy if we actually hold the fine-location permission;
            // otherwise fall back to a coarser (but still usable) accuracy request.
            val priority = if (fineGranted) Priority.PRIORITY_HIGH_ACCURACY else Priority.PRIORITY_BALANCED_POWER_ACCURACY

            val cts = CancellationTokenSource()
            continuation.invokeOnCancellation { cts.cancel() }

            fusedLocationClient.getCurrentLocation(priority, cts.token)
                .addOnSuccessListener { location ->
                    if (continuation.isActive) continuation.resume(location)
                }
                .addOnFailureListener {
                    if (continuation.isActive) continuation.resume(null)
                }
        }
    }

    private fun dispatchEmergencyAlert(alert: SOSAlertMessage) {
        val isNetworkAvailable = checkNetworkAvailability()

        if (isNetworkAvailable) {
            appendLog("[OK] Internet available: Dispatching IP Alert")
            // IP payload delivery logic goes here
            finalizeActivation()
        } else {
            appendLog("[WARN] No Internet: Falling back to Cellular SMS")
            if (ContextCompat.checkSelfPermission(applicationContext, Manifest.permission.SEND_SMS) == PackageManager.PERMISSION_GRANTED) {
                sendSMSAlerts(alert.toFormattedString())
                appendLog("[OK] SMS Alerts dispatched to contacts")
            } else {
                appendLog("[ERROR] SMS permission missing! Displaying emergency instructions.")
            }
            finalizeActivation()
        }
    }

    private fun sendSMSAlerts(message: String) {
        // getSystemService(SmsManager::class.java) requires API 31+; fall back for older devices.
        val smsManager: SmsManager = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            applicationContext.getSystemService(SmsManager::class.java)
        } else {
            @Suppress("DEPRECATION")
            SmsManager.getDefault()
        }

        val parts: ArrayList<String> = smsManager.divideMessage(message)

        _contacts.value.forEach { contact ->
            try {
                if (parts.size > 1) {
                    smsManager.sendMultipartTextMessage(contact.phone, null, parts, null, null)
                } else {
                    smsManager.sendTextMessage(contact.phone, null, message, null, null)
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }

    private fun finalizeActivation() {
        _sosState.value = SOSState.ACTIVE_EMERGENCY
        appendLog("SOS ACTIVE - Live Monitoring Engaged")
    }

    fun stopSOS() {
        _sosState.value = SOSState.COMPLETED
        _countdownProgress.value = 0f
        appendLog("Emergency sequence terminated by user.")
    }

    fun resetToIdle() {
        _sosState.value = SOSState.IDLE
        _statusLog.value = emptyList()
    }

    private fun appendLog(msg: String) {
        _statusLog.value = _statusLog.value + msg
    }

    private fun checkNetworkAvailability(): Boolean {
        val cm = applicationContext.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        val capabilities = cm.getNetworkCapabilities(cm.activeNetwork)
        return capabilities?.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET) == true
    }

    private fun triggerVibration() {
        val vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            val vibratorManager = applicationContext.getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager
            vibratorManager.defaultVibrator
        } else {
            @Suppress("DEPRECATION")
            applicationContext.getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
        }
        vibrator.vibrate(VibrationEffect.createOneShot(500, VibrationEffect.DEFAULT_AMPLITUDE))
    }
}

class SOSViewModelFactory(private val context: Context) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(SOSViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return SOSViewModel(context.applicationContext) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class: ${modelClass.name}")
    }
}

// ==========================================
// 4. MAIN ACTIVITY & ENTRY POINT
// ==========================================

class MainActivity : ComponentActivity() {
    // viewModels() delegate + factory: the ViewModel survives configuration changes
    // (e.g. rotation) instead of being recreated every time onCreate runs.
    private val viewModel: SOSViewModel by viewModels { SOSViewModelFactory(this) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            MaterialTheme(colorScheme = darkColorScheme(primary = Color(0xFFFF3B30))) {
                Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
                    MainAppLayout(viewModel)
                }
            }
        }
    }
}

// ==========================================
// 5. JETPACK COMPOSE UI COMPONENTS
// ==========================================

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MainAppLayout(viewModel: SOSViewModel) {
    var selectedTab by remember { mutableIntStateOf(0) }
    val sosState by viewModel.sosState.collectAsState()
    val context = LocalContext.current

    val permissionLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.RequestMultiplePermissions()
    ) { permissions ->
        val locationGranted = permissions[Manifest.permission.ACCESS_FINE_LOCATION] == true ||
            permissions[Manifest.permission.ACCESS_COARSE_LOCATION] == true
        val smsGranted = permissions[Manifest.permission.SEND_SMS] == true

        if (!locationGranted || !smsGranted) {
            Toast.makeText(
                context,
                "Location and SMS permissions are required for SafeSOS to alert your contacts.",
                Toast.LENGTH_LONG
            ).show()
        }
    }

    LaunchedEffect(Unit) {
        permissionLauncher.launch(
            arrayOf(
                Manifest.permission.ACCESS_FINE_LOCATION,
                Manifest.permission.ACCESS_COARSE_LOCATION,
                Manifest.permission.SEND_SMS
            )
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("SAFE SOS", fontWeight = FontWeight.Bold) },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            )
        },
        bottomBar = {
            NavigationBar {
                NavigationBarItem(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    icon = { Icon(Icons.Default.Home, contentDescription = "Home") },
                    label = { Text("Home") }
                )
                NavigationBarItem(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    icon = { Icon(Icons.Default.People, contentDescription = "Contacts") },
                    label = { Text("Contacts") }
                )
                NavigationBarItem(
                    selected = selectedTab == 2,
                    onClick = { selectedTab = 2 },
                    icon = { Icon(Icons.Default.LocationOn, contentDescription = "Location") },
                    label = { Text("Sharing") }
                )
                NavigationBarItem(
                    selected = selectedTab == 3,
                    onClick = { selectedTab = 3 },
                    icon = { Icon(Icons.Default.Security, contentDescription = "Security") },
                    label = { Text("Security") }
                )
            }
        }
    ) { paddingValues ->
        Box(modifier = Modifier.padding(paddingValues)) {
            when (selectedTab) {
                0 -> HomeScreen(viewModel)
                1 -> ContactsScreen(viewModel)
                2 -> LocationSharingScreen(viewModel)
                3 -> SecurityScreen()
            }

            if (sosState != SOSState.IDLE && sosState != SOSState.COUNTDOWN) {
                ActiveSOSOverlay(viewModel)
            }
        }
    }
}

@Composable
fun HomeScreen(viewModel: SOSViewModel) {
    val sosState by viewModel.sosState.collectAsState()
    val countdownProgress by viewModel.countdownProgress.collectAsState()
    val contacts by viewModel.contacts.collectAsState()
    val context = LocalContext.current

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.SpaceBetween
    ) {
        Text(
            text = "Everything okay?",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.SemiBold
        )

        // BIG SOS BUTTON WITH 2-SEC HOLD LOGIC
        Box(
            contentAlignment = Alignment.Center,
            modifier = Modifier
                .size(220.dp)
                .clip(CircleShape)
                .background(if (sosState == SOSState.COUNTDOWN) Color.Yellow else Color(0xFFFF3B30))
                .pointerInput(Unit) {
                    detectTapGestures(
                        onPress = {
                            viewModel.startSOSPress()
                            tryAwaitRelease()
                            viewModel.cancelSOSPress()
                        }
                    )
                }
        ) {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Text(
                    text = "SOS",
                    color = Color.White,
                    fontSize = 48.sp,
                    fontWeight = FontWeight.Black
                )
                Text(
                    text = "HOLD FOR 2 SEC",
                    color = Color.White.copy(alpha = 0.8f),
                    fontSize = 12.sp,
                    fontWeight = FontWeight.Bold
                )
            }

            if (sosState == SOSState.COUNTDOWN) {
                CircularProgressIndicator(
                    progress = { countdownProgress },
                    modifier = Modifier.fillMaxSize(),
                    color = Color.White,
                    strokeWidth = 8.dp
                )
            }
        }

        // TELEMETRY STATUS PANEL
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
        ) {
            Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.LocationOn, contentDescription = null, tint = Color.Green)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Location: Available")
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.People, contentDescription = null, tint = Color.Cyan)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Contacts: ${contacts.size} Configured")
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Default.BatteryFull, contentDescription = null, tint = Color.Green)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Battery: 85%")
                }
            }
        }

        // QUICK EMERGENCY DIAL BUTTON
        Button(
            onClick = {
                val intent = Intent(Intent.ACTION_DIAL, Uri.parse("tel:911"))
                context.startActivity(intent)
            },
            modifier = Modifier
            ... truncated ...